### ISSUE TITLE
Time offset does not work as expected

### ISSUE THREAD

**Issue by viktorheli** [Seeed-Studio/Grove_High_Precision_RTC_PCF85063TP#5]
Hello. 
I have a Grove High precession RTС module. In my module time is faster by 2 seconds per day. I decided to introduce a negative offset as written in the PCF85063TP.cpp file, lines 127 and 128:
"If the RTC time too fast: offset_sec < 0"
"If the RTC time too slow: offset_sec > 0"
But my clock has become even faster. :) I was somewhat puzzled.
I started reading the documentation for the PCF85063TP chip.
Here is a link to the datasheet:
https://www.nxp.com/docs/en/data-sheet/PCF85063TP.pdf

At first glance, there is nothing special about working with time offset. But as it turned out later, everything is said there, but it is very incomprehensible and not obvious.
An explanation can be found in the document "Improved timekeeping accuracy with PCF85063, PCF8523 and PCF2123 using an external temperature sensor".
Here is a link to this document:
https://www.nxp.com/docs/en/application-note/AN11247.pdf
There is an important note in paragraph 4.3 - Initial calibration on page 10:

"The oscillator should be tuned while the application is at the turnover temperature T0 of the crystal. The recommended workflow is given in Fig 3. In that example the clock runs by 14.6484 ppm too fast. A negative correction would maybe be expected, but the offset values ​​in Table 2 and Table 3 refer to the period time instead of to the requency. An increased oscillator frequency causes a shortened period time. Therefore, the period time must be extended. These results in the positive correction pulse values."

It follows that if time is faster, then a positive offset should be applied and vice versa. I checked and it really is. 

I replaced the code on line 146 of my PCF85063TP.cpp file with the following:
 float Eppm = (1000000.0 * Dmeas / Tmeas)*-1;  //invert the value, because if time goes faster, you need to make a positive correction and vice versa.
 // See documentation page 9 point 4.3. https://www.nxp.com/docs/en/application-note/AN11247.pdf

If you see fit, make changes to the master branch.
Thank you.

**Comment by ackPeng** [comment]
@viktorheli Thank you very much for your suggestion, we will study it carefully and update the repository

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
